name: Database Keep-Alive
on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Add this to enable manual triggers

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Application
        run: |
          curl -X GET https://www.aiutils.site/api/healthcheck
